GEMINI_API_KEY = "AIzaSyBurFaHApHTOd3hHygQGvqVx4qSSJbkX8A"


[GOOGLE_CREDENTIALS]
type = "service_account"
project_id = "distributed-inn-483604-q9"
private_key_id = "07570b025f5e7c86962b87e2aa86eba785f7138a"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCth6Z0kaB+89Gb
VSiCmB+zhv6/7orvOfzhYe+fN053EnBRvhsFJ/36NcYj92lN33AXYze9aATizMYn
VnZaHaNJZX0KPToUKf8GFChQQ4NFAiqx2G40wWkov8fPb4pGi9rb/UmanKD/d2y5
JGrU6WIpFDxb5GoLYNYF+4gF7k0WFsrOsCOhtnhzafahu3Jq4gFaLw+Usvrp0FPK
Y4PtCocmsZVtIWk3R9w4uL20bkxVHLSf+PdfgTFAh+Vpw/Ooh3e9w1rXX2y2u9Yh
h1+M0BPdBa5pizxJgUFWBrMr16M5Yihp93b5CXFWSPrYPE95wXfJ292P3zPg5tTx
E3uPZenRAgMBAAECggEAIYs5yYnHARNnnsO453m5kw4S244kjDbk47p3RAtAXzMQ
xDRf68C9zyqq6RPv5q488EBtK29alm7oFP2ZNjVJdawpHhwUyIYPtqCZ5F4Ql3vi
Peus7gS/K7Ha0YXpsFZjkafmHP2O/6MZwLZB8nNE1tUDD+5Y82ceKBzlv+O/QfgG
lca7XnEK1/WrB5MvncMR3oPgefVXmXGcFQxNt6fc87dQL3K4BGznod8G/Vd6cTA9
LNuBBFAgzSzvZ4nJkOJyzxnqqZ1Fhoi+6z2P6kNSPIVGkcr78ZFGnNa6IykLeX56
Wlcia+xMS7FWglmmEcvhVMhTJUZ9LGO5Kc9Jte9meQKBgQDzw4MicdwL10KvQLn1
MFSt5SSpnG5QHbN1R+Dzmh3sVJk2DzMJG/gp0XfRTmPL9lnpBizD0thi+tOcroYW
/kBfxmW+69HHZEsHlhthsqTZLinI2Fvrjpf/UOA+ogw/TJVtTHSnKM70OsuVh8zv
xziQwIoCOn9Y6hLdXXP94URPpQKBgQC2PZjzYbJypunrLUUewl0T5HhwYUpyBK4C
fxEiFQltwZH0HBtZHz5G2lfAL+AMtWW4y6/FlViCLz0bsG/Susl6sINkVqepBiGa
pER49eD59hcshlUO8Xed5tom3M27T95TIXEN2X09drbfSJI0B6Z0GjXMyscjLbGX
yCdWDHAZvQKBgA3APLiHtcMRPJjITPUw6cX5hCzxPyPT2RjHmkADtKZtS0tKZjWg
V0p8n4a2JlkOJ5pGl+XgEgbbYW6YRcYsR5NfjMPNZ8MYvEbMR/Ul77i0qvTCh8Tt
AVQMyumdmJVFi7RjuLzpR2ttmahwxbXNBjrcMazYgfCRG8lTCUUMHR9lAoGBALHR
ustIOcHLghW6b2ZLCl0dojMti2FjlZLT/5i85B1XMh35yumUJcUmyVa6oChmW2IM
RW9KgTlN9Jdu+j2pimyPjTU7pI61b9afkDxi1mmwKP6F+LsC+89z8MrYylmJ3gpJ
aDG2VJDDpD6MZjQkftNsu7Ae8F4v+Mh8QX2h10QVAoGALg9a4tm0QPg7RC8z1mWf
yyAENFXOutXhAMjrvmqcse2HU8n/JWSe7NiOoxR5Yg53ghs4ghroLx6elWNSNfGa
3GX9dowbelBLQ6hFjfLdrdRMSMJMSS+n5nBhCqXzpmQ6X7oM+/Xsg/GjfgHykGk9
LaSbAJlUgR/KBCHffXF38A0=
-----END PRIVATE KEY-----"""
client_email = "streamlit-sheets-access@distributed-inn-483604-q9.iam.gserviceaccount.com"
client_id = "102253214798373812229"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-sheets-access%40distributed-inn-483604-q9.iam.gserviceaccount.com"
